### ISSUE TITLE
Expose heat/cool settings on zone entities

### ISSUE THREAD

**Issue by cemilbrowne** [TheNoctambulist/hass-airtouch#6]
### Checklist

- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).

### Proposal

I'm a little biased - I wrote the Airtouch homebridge addon. :)

In order to expose Airtouch zones to Homekit correctly, it's much easier if the individual zones have heat/cool/auto controls (matching the parent AC).  If you set one, it sets all, so they stay sync'd.  This way I can just expose Zone entities to homekit, and deal with them as if they're independent AC units.

**Comment by TheNoctambulist** [comment]
The heat/cool modes are already exposed for each zone climate entity as described in the [README](https://github.com/TheNoctambulist/hass-airtouch?tab=readme-ov-file#snowflake-climate-zone-climatezone_name)

The available modes for each zone changes dynamically based on the current AC mode because a zone can only be off or in the same mode as the AC, all zones are fixed to the AC mode.

**Comment by TheNoctambulist** [comment]
I've implemented an optional feature to allow the zone climate entities to change the parent AC HVAC mode. I think this will allow you to have the behaviour you want.
Note that if you want the zones to automatically trigger to the AC to turn on you will need to activate the "Turn on AC when a zone is being turned on" setting in the AirTouch console settings.

I'll publish a release with this feature once I've completed some additional testing.
